version: "3.8"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build: .
    command:
      [
        "./wait-for-it.sh",
        "rabbitmq:5672",
        "--",
        "celery",
        "-A",
        "celery_config.celery_app",
        "worker",
        "--loglevel=info",
        "-Q",
        "video_processing",
        "-c",
        "2",
      ]
    depends_on:
      - rabbitmq

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
    depends_on:
      - celery
